### ISSUE TITLE
Issues Remaining 

### ISSUE THREAD

**Issue by Chris1221** [Chris1221/coR-ge#1]
January 12 Meeting 
- [ ] The clusters aren't obviously separable, so maybe add as a third dimension a density peak to see if the groups really are different in the following:

![](https://raw.githubusercontent.com/Chris1221/coR-ge/master/assets/images/sk.png)
- [ ] Incorporate true positive gradient instead of absolute number of TPs
- [ ] Sweep over concentrations for cluster enrichment
- [x] UK10K Data access
